title: Artsciephile
description: Dari atom hingga alam semesta, ketahui gimana segalanya bekerja.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

social:
  instagram: https://www.instagram.com/artsciephile
  tiktok: https://www.tiktok.com/@artsciephile
  youtube: https://www.youtube.com/@artsciephile